Copyright 2014 Autodesk, Inc.  All rights reserved.

Use of this software is subject to the terms of the Autodesk license 
agreement provided at the time of installation or download, or which 
otherwise accompanies this software in either electronic or hard copy form.   
//////////////////////////////////////////////////////////////////////////////

This program demonstrates the use of some of the AcDbCurve protocol. It defines the functions projectEllipse() and offsetEllipse().

1. Create an ellipse in AutoCAD.
2. Load the arx application.
3. Command: curves 
This creates a new ellipse. The project option creates an ellipse that is the result of a projection onto the plane with normal <1,1,1>. The Offset option creates one that is offset 0.5 drawing units from the original. 
